### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by nosamanuel** [nosamanuel/cottonmouth#3]

**Comment by brettatoms** [comment]
This is something I might be interested in working on.  Is the plan to be compatible with Python 2.7 and Python 3.x or drop Python 2.7 support altogether?

**Comment by adamlwgriffiths** [comment]
It's definitely not working ootb

```
>>> import cottonmouth.tags
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<snip>/.venv/lib/python3.8/site-packages/cottonmouth/tags.py", line 4, in <module>
    class Tag(unicode):
NameError: name 'unicode' is not defined
```

The `python3` branch seems to work.
Any plans to release that?
